
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 04 20:09:55 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 2;
  public static final int function = 8;
  public static final int corcheteCe = 49;
  public static final int distinto = 40;
  public static final int suma = 51;
  public static final int parentesisCerrado = 31;
  public static final int numeric_real_const = 45;
  public static final int mod = 10;
  public static final int array = 16;
  public static final int dosPuntos = 29;
  public static final int INTEGER = 32;
  public static final int coma = 43;
  public static final int igual = 28;
  public static final int ident_while = 21;
  public static final int CHARACTER = 34;
  public static final int ident_case = 25;
  public static final int begin = 3;
  public static final int ident_do = 22;
  public static final int menorIgual = 37;
  public static final int end = 4;
  public static final int parentesisAbierto = 30;
  public static final int menos = 41;
  public static final int then = 19;
  public static final int menor = 36;
  public static final int dosPuntosIgual = 35;
  public static final int var = 6;
  public static final int EOF = 0;
  public static final int mayorIgual = 39;
  public static final int error = 1;
  public static final int mayor = 38;
  public static final int ident_const = 5;
  public static final int or = 12;
  public static final int procedure = 7;
  public static final int ident_for = 23;
  public static final int punto = 27;
  public static final int puntosRango = 50;
  public static final int REAL = 33;
  public static final int puntoComa = 26;
  public static final int of = 15;
  public static final int record = 17;
  public static final int corcheteAb = 48;
  public static final int ident_if = 18;
  public static final int Identificador = 47;
  public static final int and = 11;
  public static final int not = 13;
  public static final int ident_else = 20;
  public static final int numeric_integer_const = 44;
  public static final int asterisco = 42;
  public static final int string_const = 46;
  public static final int div = 9;
  public static final int to = 24;
  public static final int type = 14;
}

